---
- name: Install PostgreSQL
  ansible.builtin.import_tasks: install.yaml

- name: Configure PostgreSQL
  ansible.builtin.import_tasks: configure.yaml

- name: Manage PostgreSQL Service
  ansible.builtin.import_tasks: service.yaml

- name: Verify PostgreSQL Setup (Users & Databases)
  ansible.builtin.import_tasks: verify.yaml

- name: Initialize Attendance API Schema
  ansible.builtin.import_tasks: schema.yaml
