---
- name: Install PostgreSQL
  import_tasks: install.yaml

- name: Configure PostgreSQL
  import_tasks: configure.yaml

- name: Manage PostgreSQL Service
  import_tasks: service.yaml

- name: Verify PostgreSQL Setup (Users & Databases)
  import_tasks: verify.yaml
