---
- name: Install Redis
  ansible.builtin.import_tasks: install.yml

- name: Enable and Start Redis Service
  ansible.builtin.import_tasks: service.yml

- name: Verify Redis Installation
  ansible.builtin.import_tasks: verify.yml
