---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: instance
ansible:
  cfg:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
      remote_tmp: /tmp/.ansible/tmp
      host_key_checking: false
      verbosity: 1
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"
  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
    verify: verify.yml
verifier:
  name: ansible
