- name: Create JCasC directory
  file:
    path: /var/lib/jenkins/casc_configs
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Deploy JCasC configuration
  template:
    src: casc.yaml.j2
    dest: /var/lib/jenkins/casc_configs/casc.yaml

- name: Configure JCasC path
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
    line: 'JAVA_ARGS="-Dcasc.jenkins.config=/var/lib/jenkins/casc_configs/"'
  notify:
    - Restart Jenkins
