- name: Copy plugin list
  copy:
    src: plugins.txt
    dest: /tmp/plugins.txt

- name: Create plugin manager directory
  file:
    path: /opt/jenkins
    state: directory
    mode: '0755'

- name: Download Jenkins Plugin Manager Tool
  get_url:
    url: https://repo.jenkins-ci.org/releases/io/jenkins/plugin-management/plugin-management-cli/2.13.2/plugin-management-cli-2.13.2.jar
    dest: /opt/jenkins/jenkins-plugin-manager.jar
    mode: '0755'

- name: Install Jenkins Plugins
  shell: |
    java -jar /opt/jenkins/jenkins-plugin-manager.jar \
      --plugin-file /tmp/plugins.txt \
      --plugin-download-directory /var/lib/jenkins/plugins
  notify:
    - Restart Jenkins
