---
scylla_cluster_name: OTMS-Cluster

scylla_seed_nodes: "{{ ansible_facts.default_ipv4.address }}"

scylla_listen_address: "{{ ansible_facts.default_ipv4.address }}"

scylla_rpc_address: "{{ ansible_facts.default_ipv4.address }}"

scylla_endpoint_snitch: SimpleSnitch

scylla_developer_mode: true

scylla_service_name: scylla-server
