---
scylla_package: scylla

scylla_cluster_name: OTMS-Cluster
scylla_seed_nodes: "{{ ansible_default_ipv4.address }}"
scylla_listen_address: "{{ ansible_default_ipv4.address }}"
scylla_rpc_address: "0.0.0.0"
scylla_api_port: 10000
scylla_native_transport_port: 9042
scylla_endpoint_snitch: SimpleSnitch
scylla_read_timeout: 5000
scylla_write_timeout: 2000
scylla_cas_timeout: 1000
