---
# Package & Service
scylla_package: scylla
scylla_service_name: scylla-server

# Cluster Configuration
scylla_cluster_name: "OTMS-Cluster"
scylla_listen_address: "{{ ansible_facts.default_ipv4.address }}"
scylla_seed_nodes: "{{ scylla_listen_address }}"
scylla_rpc_address: "{{ ansible_facts.default_ipv4.address }}"
scylla_endpoint_snitch: "SimpleSnitch"
scylla_developer_mode: true

# Ports
scylla_native_transport_port: 9042
scylla_api_port: 10000

# CQL Connectivity
scylla_cql_host: "otms.scylladb.internal"
scylla_cql_port: "{{ scylla_native_transport_port }}"
scylla_cql_wait_timeout: 180

# Application Keyspaces
scylla_application_keyspace: "employee_db"
scylla_keyspaces:
  - "{{ scylla_application_keyspace }}"

# Replication
scylla_replication_class: "SimpleStrategy"
scylla_replication_factor: 1
