---
plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  "tag:Name": "dev-otms-scylla-ec2"
  instance-state-name: running

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address

groups:
  scylladb: true

keyed_groups:
  - prefix: environment
    key: ec2_tags.Environment

  - prefix: application
    key: ec2_tags.Application

  - prefix: owner
    key: ec2_tags.Owner
