
postgresql_version: "16"
postgresql_service_name: postgresql
postgresql_port: 5432

postgresql_conf: /etc/postgresql/16/main/postgresql.conf
postgresql_hba: /etc/postgresql/16/main/pg_hba.conf
postgresql_backup_dir: /opt/postgresql-rollback

postgresql_listen_addresses: "*"
postgresql_allowed_cidr: "10.0.0.0/16"
postgresql_auth_method: scram-sha-256

postgresql_database: attendance_db
postgresql_user: postgres
postgresql_password: password
